# Generated by Django 5.2.16 on 2026-08-16 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('decision', models.CharField(max_length=64)),
                ('likely_condition', models.CharField(blank=True, default='', max_length=255)),
                ('assessment_summary', models.TextField(blank=True, default='')),
                ('kas', models.FloatField(blank=True, null=True)),
                ('lcs', models.IntegerField(blank=True, null=True)),
                ('dcs', models.FloatField(blank=True, null=True)),
                ('patient_snapshot', models.JSONField(default=dict)),
                ('result_snapshot', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
